jobs:
  build:
    docker:
      - image: python:3.6
    steps:
      - name: Checkout
        uses: actions/checkout@v2  # Use the official checkout action

      - name: Install dependencies and check
        run: |
          pip install -r requirements.txt
          python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies and run tests
        run: |
          pip install -r requirements.txt
          python manage.py test taskManager

  release:
    machine: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker registry and push
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker build -t $DOCKER_USERNAME/django.nv .
          docker push $DOCKER_USERNAME/django.nv

  integration:
    docker:
      - image: python:3.6
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run integration step
        run: |
          echo "This is an integration step"
          exit 1
      when: always  # Correct indentation

  prod:
    docker:
      - image: python:3.6
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to production
        run: echo "This is a deploy step."

workflows:
  version: 2
  django:
    jobs:
      - build
      - test:
          requires:
            - build 
      - integration:
          requires:
            - test
      - prod:
          type: approval
          requires:
            - integration
